#!/usr/bin/env bash

set -e

echo "--> Setting up test database"
rake db:test:prepare

echo "--> Running system tests in development"
rake test:system

echo "--> Running Cypress tests in development, starting all static servers and proxying requests"
rake cypress:run

echo "--> Precompiling all static site assets with rake assets:precompile"
rake assets:precompile

echo "--> Running tests in production, *not* starting servers and serving files instead of proxying"
RAILS_ENV=production CYPRESS_RAILS_CYPRESS_OPTS="--env RAILS_ENV=production" rake cypress:run
