source "https://rubygems.org"

gem "jekyll"
gem "minima"

group :jekyll_plugins do
  gem "jekyll-feed"
end

install_if -> { RUBY_PLATFORM =~ %r!mingw|mswin|java! } do
  gem "tzinfo"
  gem "tzinfo-data"
end

gem "wdm", "~> 0.1.1", :install_if => Gem.win_platform?

